### ISSUE TITLE
do we support DT_INIT?

### ISSUE THREAD

**Issue by jim-wilson** [riscv-non-isa/riscv-elf-psabi-doc#132]
Our policy is that we don't support .init or .fini sections.  However, the GNU toolchain is still creating binaries and shared libraries with DT_INIT set which appears to conflict with that.  That leads to several questions.  Should we have DT_INIT support?  Given that we already have linux distros built with DT_INIT support, is it possible to drop support for it, or would that be an unacceptable ABI break?  There is also a similar issue with DT_FINI.  Though DT_INIT seems to be the more immediate problem as a glibc libc.so has DT_INIT but not DT_FINI.

This came up as glibc is adding better support for systems without ini/fini sections, and those patches unexpectedly broke RISC-V support.  Leading to questions about whether RISC-V really dropped support for init/fini sections or not.

A search of Fedora RISC-V libraries shows about half a dozen projects have libraries with DT_INIT/DT_FINi.  One of those is GNU libc which is already under discussion.  One is numactl.  I looked at that one, and I see that the Makefile.am has -Wl,-init,numa_init -Wl,-fini,numa_fini so this is at least not the toolchain's fault.  But then this does bring up another question as to what the toolchain should do in this case.  Give an error when -Wl,-init is used?  Or try to convert a linker -init option into an init_array entry?  I'd rather give a linker error and fix the package.

**Comment by jim-wilson** [comment]
Here is a pointer to the glibc thread
https://sourceware.org/ml/libc-alpha/2020-02/msg00896.html

**Comment by aswaterman** [comment]
“Fix the package” sounds cleanest, but I don’t have a clear idea of how pervasive those changes would be. Given the relatively small number of packages with DT_INIT (assuming I understood the post on libc-alpha correctly), perhaps the scope is narrow enough.

**Comment by fweimer** [comment]
> I looked at that one, and I see that the Makefile.am has -Wl,-init,numa_init -Wl,-fini,numa_fini so this is at least not the toolchain's fault.

I think the toolchain should be consistent, though: binutils should only support those features which are also implemented in glibc (or have a reasonable path towards a future implementation). The reason is that it's otherwise impossible to write cross-compilation-compatible feature tests, you have to hard-code expectations (like we do in glibc now with the `ELF_INITFINI` macro). For RISC-V, lack of `-init`/`-fini` support (or `DT_INIT`/`DT_FINI` support) is a conscious choice, not a current shortcoming of the current glibc implementation, so it's reasonable to remove it from the linker for RISC-V. It will also clearly identify the numactl build issue, making porting easier.

**Comment by jrtc27** [comment]
We can certainly change this to be an RFC 2119 SHOULD NOT. A year down the line, how does the Linux/glibc world feel about making this a MUST NOT? That'd be preferable, and existing binaries can still work, just rebuilding might fail, but is that too disruptive for you?

**Comment by fweimer** [comment]
Existing glibc binaries that depend on `_init` probably will not work because current glibc does not run `_init` anymore. All new architectures behave that way because the generic default has changed, with existing architectures predating RISC-V overriding it.

**Comment by jrtc27** [comment]
Right, yes, the dynamic linker runs `_init` for dynamically-linked binaries, only statically-linked ones will continue to work.
