### ISSUE TITLE
Remove further reference to R_RISCV_GPREL_[IS]

### ISSUE THREAD

**Issue by jrtc27** [riscv-non-isa/riscv-elf-psabi-doc#205]
We currently still say the following:

> **GP-Relative Relocations**: If `symbol` is within the range of a signed 12-bit
> immediate offset from `__global_pointer$`, then the address can be loaded with a
> single instruction which has one relocation, a `R_RISCV_GPREL_I` or
> `R_RISCV_GPREL_S`.
> 
> The instruction is an I-Type instruction (add immediate or load) with an
> `R_RISCV_GPREL_I` or an S-type instruction (store) with an `R_RISCV_GPREL_S`
> relocation. The following assembly show loading a gp-relative address:
> 
> ```
>      addi a0, gp, 0          # R_RISCV_GPREL_I (symbol)
> ```
> 
> This relies on the value of `__global_pointer$` being loaded into `gp` (aka
> `x3`). This can be used by linker relaxation to delete the `lui` instruction.

There was never any assembly syntax for that and the relocations have since been removed due to being internal binutils relocations. We should remove this section.

**Comment by kito-cheng** [comment]
I believe this issue is resolved by this https://github.com/riscv/riscv-elf-psabi-doc/pull/199 :)

**Comment by jrtc27** [comment]
No, that's why this issue says "further". I missed these in my original PR.

**Comment by kito-cheng** [comment]
Oh, I got your point, I guess I can working on writing `__global_pointer$` in next few days and remove that, or are you already working on that?

**Comment by jrtc27** [comment]
We already have https://github.com/riscv/riscv-elf-psabi-doc/blob/master/riscv-elf.md#calculation-symbols, I think the quoted section just needs deleting.
