### ISSUE TITLE
typo for LO12_I and LO12_S

### ISSUE THREAD

**Issue by unicornx** [riscv-non-isa/riscv-elf-psabi-doc#234]
riscv-elf.adoc, Table 3. Relocation types
![image](https://user-images.githubusercontent.com/2476165/146858792-ff6e7b5b-9ed2-4469-9b76-90c488b77f15.png)

Are they typo? High -> Low

And I would prefer more specific description, now they look same. Add some words to clarify one is for I-Type and another is for S-Type would be better.

**Comment by jrtc27** [comment]
> Are they typo? High -> Low

Yes, thanks

> And I would prefer more specific description, now they look same. Add some words to clarify one is for I-Type and another is for S-Type would be better.

That's what column 4 is for and clearly states.

**Comment by unicornx** [comment]
For the first typo, will you raise a PR? Or let me submit it?
