### ISSUE TITLE
question on description about  PLT

### ISSUE THREAD

**Issue by unicornx** [riscv-non-isa/riscv-elf-psabi-doc#235]
riscv-elf.adoc, section : "Program Linkage Table"

in code sample for the first entry:
```
srli   t1, t1, log2(16/PTRSIZE) # .got.plt offset
```
I think the comment should be ".rela.plt offset", because I checked the glibc function, `_dl_fixup()`, looks like it will use the value of t1 to get the relocation entry in .rela.plt. Not sure if my understanding is correct.

**Comment by kito-cheng** [comment]
.rela.* section are used for recording relocation infos, and just double checked with binutils[2] and lld[3], they all fill .got.plt, so I think the description is correct :p 

[1] https://github.com/bminor/glibc/blob/master/sysdeps/riscv/dl-trampoline.S#L59
[2] https://github.com/bminor/binutils-gdb/blob/master/bfd/elfnn-riscv.c#L215
[3] https://github.com/llvm/llvm-project/blob/main/lld/ELF/Arch/RISCV.cpp#L181

**Comment by jrtc27** [comment]
This is a confusing part of PLTs for those not familiar with how they work. It is the offset within .got.plt of the PLT entry that was called. However, .rela.plt is a list of R_RISCV_JUMP_SLOT relocations and, crucially, kept in the same order as the .got.plt entries it relocates. This means that RTLD can scale t1 by `sizeof(Elf_Rela) / sizeof(void *)` to get the .rela.plt offset, and thus the relocation with the symbol to bind. This design is shared by most architectures; certainly not new for RISC-V.

**Comment by jrtc27** [comment]
(https://github.com/bminor/glibc/blob/a51faeee6ae68da63e65eb0a1eb6c9ec2ce2148b/sysdeps/riscv/dl-trampoline.S#L56 is where glibc does the scaling, https://github.com/freebsd/freebsd-src/blob/1a0a41b10566e75e77e7efbc8475622b6a37ffbf/libexec/rtld-elf/riscv/rtld_start.S#L91 is where FreeBSD does it)
