### ISSUE TITLE
GCC generates non-position-independent code under -cmodel=medany

### ISSUE THREAD

**Issue by palmer-dabbelt** [riscv-non-isa/riscv-elf-psabi-doc#245]
The objects we generate from GCC for the medium code model, aka -cmmodel=medany, are not position independent unless -fPIC is also passed.  This violates the psABI spec, which says under the medium code model section that "This code model is position independent."

**Comment by aswaterman** [comment]
@palmer-dabbelt What's GCC doing that's non-PIC?

**Comment by palmer-dabbelt** [comment]
Using PC-relative addressing modes to resolve absolute symbols -- I guess one could argue that's a linker problem or a compiler problem, but IMO the relocations are pretty clear about being PC-relative and thus it's a GCC bug.  One could imagine rejecting these at link time, but that would break existing use cases -- there's a bit about deprecating the weak undefined symbol trick, but all absolute symbols are equally broken.  Dropping these use cases might be the right thing to do, as there's certainly bugs here in binutils, but there are currently users of them without a suitable replacement (Linux, for one, but that specific use is somewhat silly).

One could imagine having something between -fPIC (ie, code suitable for shared libraries) and -mcmodel=medany (ie, position-independent but without the extra bits for shared libraries), maybe via either absolute-tolerant relocations (properly GOT or some other constant table) or by absolute-banning relocations (whether that breaks existing use cases or now).  IMO it's way too late in the release cycle to do that now,, though, so that leaves the only option to make GCC match the current spec being to drop the bad code gen modes (ie, "-mcmodel=medany -fno-PIC").

That's what I'd originally suggested, as I thought the spec was past the point where it could be changed, but nhe general consensus on the toolchain call today was that I should submit this as a spec bug.  I don't really care either way, just trying to figure out how to stop generating code that violates the spec.

**Comment by aswaterman** [comment]
@jrtc27 made the point that `-mcmodel=medany -pie` works just fine, which from simple examples GCC seems to be handling just fine.  To me, that does mean that medany is position-independent.

I don't think we should drop anything from this GCC release.

**Comment by jrtc27** [comment]
Isn't -fPIE the thing in between? It's basically the same, except it uses the GOT for anything that might require a copy relocation, though that's really an orthogonal thing.

Using absolute symbols is fine at link time, so long as they're within range (or, in the case of binutils, it can mangle your instructions to fix your bogus input). That doesn't make the input any less position-independent, it just means you made it position independent at link time, just like if you linked libfoo_pic.a into a position-dependent executable.

I don't think GCC's current behaviour is wrong here, other than the weak symbol issue that's already documented.

**Comment by cmuellner** [comment]
@jrtc27 would it make sense to clarify this with an informal note in the document?

E.g. "Note, that although the generated code is position independent, it might still be necessary to enable additional compiler flags (e.g. `-fPIC`) when building position-independent ELF objects (e.g. shared libraries)."

**Comment by palmer-dabbelt** [comment]
I sent a GCC patch to describe the behavior.  IMO it's always better to have stuff in the spec than just in review comments, but we've got a lot of stuff in the comments so I'm fine either way.
