### ISSUE TITLE
The psABI is not frozen, but says it is

### ISSUE THREAD

**Issue by palmer-dabbelt** [riscv-non-isa/riscv-elf-psabi-doc#246]
As per the discussion in this toolchain meeting we're in, the psABI has not actually been frozen and is not actually up for public review.  This conflicts with the psABI tag, the text of the specification, and some emails announcing a public review.

**Comment by SamB** [comment]
Well, I was starting to write some stuff that seems suspiciously like a paraphrase of the following comment:
<https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/fdcc856efec031beaea41134c166811fbac4223f/prelude.adoc?plain=1#L2-L18>

So it really doesn't matter what the official status is, the ABI itself is basically set in stone. At the same time, document text could fail to match reality, which can be fixed; also, new things *can* be added.

**Comment by kito-cheng** [comment]
psABI spec 1.0 has ratified and released, so close.
