### ISSUE TITLE
Disclaim that ILP32E is not stable

### ISSUE THREAD

**Issue by jrtc27** [riscv-non-isa/riscv-elf-psabi-doc#249]
RV32E is not ratified, so it is not possible for us to promise that the ILP32E ABI is stable. We should clearly indicate that it is not stable yet despite what the rest of the document may say.

**Comment by aswaterman** [comment]
In case anyone is wondering, ratifying RV32E is something we're hoping to do in the next few months.  I wouldn't expect any changes (but all of the usual caveats apply).
