### ISSUE TITLE
Frame pointer usage issue for C and C++

### ISSUE THREAD

**Issue by kito-cheng** [riscv-non-isa/riscv-elf-psabi-doc#263]
Review comment come from @anderslindgren-iar and Anders Berg(IAR) https://lists.riscv.org/g/tech-toolchain-runtime/message/344

> The presence of a frame pointer is optional. If a frame pointer exists it must reside in x8 (s0), the register remains callee-saved.

Anders: It should perhaps be mentioned that C and C++ should never use a frame pointer.

Paul Curtis (Segger): In general this is true, but C99 VLA implementation would require a frame pointer.

**Comment by jrtc27** [comment]
I don't see why the ABI needs to say anything about this? It doesn't matter, implementations can do what they like, it's not exposed.

**Comment by AndersBerg-IAR** [comment]
> I don't see why the ABI needs to say anything about this? It doesn't matter, implementations can do what they like, it's not exposed.

There is one case though when we need to specify the calling convention for C/C++ compilers supporting VLA. It is when (at least) one of the function arguments is a VLA. This is the only case when one may need a specified calling convention as far as I understand. In all other cases the calling convention should be the same as if VLAs where not supported. It should be mentioned in the document that the calling convention in such cases is not specified yet.

**Comment by kito-cheng** [comment]
Frame pointer is optional in most case, and only required when variable length argument and variable length array, compiler could use framer pointer register if possible in current calling convention, so I am not sure why we need a special calling convention for that?

**Comment by fweimer-rh** [comment]
@AndersBerg-IAR Don't VLA arguments decay to a pointer in C?

Compilers may have to use a frame pointer if the frame size is not fixed, but this is an internal implementation detail of each function, with no ABI implications. (I assume DWARF on RISC-V already has support for a frame pointer.)

**Comment by AndersBerg-IAR** [comment]
> Frame pointer is optional in most case, and only required when variable length argument and variable length array, compiler could use framer pointer register if possible in current calling convention, so I am not sure why we need a special calling convention for that?

As I said earlier, it is only needed when one of the function arguments is a VLA. In such cases we need to specify the following as far as I understand:

1.	Which register to use as a frame pointer (presumably register s0).
2.	How to pass multiple VLA arguments.
3.	How the function arguments will be placed on the stack and in which order.
4.	If the called function should deallocate the stack at return and how.

**Comment by AndersBerg-IAR** [comment]
> 

You are of course right Florian! This is the best way to implement it, but it should still be mentioned in the ABI how the C/C++ compilers should handle VLAs in order to avoid further confusion.

**Comment by jrtc27** [comment]
No it shouldn’t. It’s not ABI, it’s an internal implementation detail.
