### ISSUE TITLE
More clarification for passing floating point value on GPR

### ISSUE THREAD

**Issue by kito-cheng** [riscv-non-isa/riscv-elf-psabi-doc#267]
Review comment come from @anderslindgren-iar and Anders Berg(IAR) https://lists.riscv.org/g/tech-toolchain-runtime/message/344

> without extending the integer to XLEN bits,

Anders: This may need an additional clarification. If the higher bits are regarded as undefined, it should be clear it is so.

**Comment by asb** [comment]
I thought this was clear enough in the context of the doc, but wouldn't be opposed to making it more obvious by adding something like "(i.e. the value of any bits beyond FLEN are undefined)".
