### ISSUE TITLE
Too many floating point ABI variants?

### ISSUE THREAD

**Issue by asb** [riscv-non-isa/riscv-elf-psabi-doc#27]
The rules for the floating point calling convention result in rather a high number of mutually incompatible ABIs. Is this desirable?

Currently we have:
* RV32E
* RV32I
* RV32IF
* RV32G (RV32IFD)
* RV64I
* RV64IF
* RV64G (RV64IFD)
* RV64IFDQ

Plus of course RV128 in the future. There is no RV32IFDQ as this combination is disallowed by the ISA specification.

**Comment by aswaterman** [comment]
Most of those only show up for embedded systems, which only need to support one ABI.

Unix systems generally use only RV32G and RV64G (and later RV64GQ).  So I don't think this is actually a problem.

**Comment by asb** [comment]
I think embedded systems can't totally be written off - a proliferation of ABIs is still a challenge if they use code that's not written in C. I agree it's not a huge deal though. I suppose the real fix here is perhaps making it clear what the common ABIs that are expected to be  RV32G and RV64G are the common ABIs supported by the majority of tools. Then there's the additional question of whether it's really worth introducing a new ABI for the Q extension. For instance, an option available to us is to recommend that implementers of Q stick to the RV64G ABI.

**Comment by aswaterman** [comment]
Yeah, I don't mean to dismiss embedded systems.  But, as you said, we should make it clear what ABIs we expect people to actually use.  My guess is that means RV32G/RV64G for Unix-like systems, and RV32I/RV32IF/RV64I/RV64G for embedded systems.

You're probably right about the Q ABI.  For some applications, it will even be more performant to use the G ABI, because the stack frames will be more compact.  Most applications will _never_ put a long double in a callee-saved register, yet will always have to spill 128 bits.

**Comment by aaronfranke** [comment]
@asb What do you mean by *mutually* incompatible? I thought RV64I software can run on RV64IF, RV64G, and RV64GQ, etc? Same with RV64IF software, it should run on RV64G, RV64GQ, and any other RV64 architecture that supports IF, right?

**Comment by jrtc27** [comment]
The terminology in this issue is very old (I assume). RV64I software can run on RV64IF, but it will use the LP64 ABI whereas RV64IF software can use either the LP64 ABI or the LP64F ABI, and the two are not compatible.

**Comment by asb** [comment]
I don't think there's really anything more to discuss on this issue so I'll mark it closed.

ABIs like LP64F probably get very little real-world testing, but on the other hand it's implemented as a fairly straight-forward parameterisation of the standard ABI rules so hopefully isn't overly bug-prone.
