### ISSUE TITLE
Define GOT before use

### ISSUE THREAD

**Issue by kito-cheng** [riscv-non-isa/riscv-elf-psabi-doc#271]
Review comment come from @anderslindgren-iar and Anders Berg(IAR) https://lists.riscv.org/g/tech-toolchain-runtime/message/344

> global offset table (GOT)

Anders: Where is the specification for GOT (how can one find it)?

```
    # Load value from a local symbol 
0:  auipc a0, %pcrel_hi(symbol)
    lw    a0, %pcrel_lo(0b)(a0)
    # Store value to a local symbol 
1:  auipc a0, %pcrel_hi(symbol)
    sw    a1, %pcrel_lo(1b)(a0)
    # Calculate address of a local symbol 
2:  auipc a0, %pcrel_hi(symbol)
    addi  a0, a0, %pcrel_lo(2b)
    # Calculate address of non-local symbol 
3:  auipc  a0, %got_pcrel_hi(symbol)
    l[w|d] a0, a0, %pcrel_lo(3b)
```

Anders: The example is pointless if one cannot find the specification for GOT.
Should it not be an additional case of how to read a non-local symbol?

**Comment by jrtc27** [comment]
https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-elf.adoc#global-offset-table

**Comment by jrtc27** [comment]
> Should it not be an additional case of how to read a non-local symbol?

No, because there is no special sequence. The load/store cases for local symbols are only shown because you can fold the addi for the address calculation into the load or store immediate offset, but you cannot fold a load into a load or store.

**Comment by kito-cheng** [comment]
As @jrtc27 mention, we've defined later, but I think adding an explicitly forward reference could be better, see https://github.com/riscv-non-isa/riscv-elf-psabi-doc/pull/277
