### ISSUE TITLE
More clarification on Dynamic Linking Chapter

### ISSUE THREAD

**Issue by kito-cheng** [riscv-non-isa/riscv-elf-psabi-doc#272]
Review comment come from @anderslindgren-iar and Anders Berg(IAR) https://lists.riscv.org/g/tech-toolchain-runtime/message/344

> Chapter 6. Dynamic Linking
> Any functions that use registers in a way that is incompatible with the register convention of the ABI in use must be annotated with STO_RISCV_VARIANT_CC, as defined in Section 8.4.
> ...

Anders: The title and the text do not seem to be connected. Is this about dynamic linking? It does not look like that. Please explain better!

**Comment by jrtc27** [comment]
This is explained by the non-normative note immediately below the paragraph
