### ISSUE TITLE
Clean up for Table 13. TLS models

### ISSUE THREAD

**Issue by kito-cheng** [riscv-non-isa/riscv-elf-psabi-doc#273]
Review comment come from @anderslindgren-iar and Anders Berg(IAR) https://lists.riscv.org/g/tech-toolchain-runtime/message/344

| Mnemonic | Model | Compiler flags |
|----------|:-------------|:------|
| TLS LE | Local Exec | -ftls-model=local-exec |
| TLS IE | Initial Exec | -ftls-model=initial-exec |
| TLS LD | Local Dynamic | -ftls-model=local-dynamic |
| TLS GD | Global Dynamic | -ftls-model=global-dynamic |

Anders: The compiler flags are toolchain specific and may be different depending on which toolchain one is using.

**Comment by nick-knight** [comment]
I would support moving the flags to https://github.com/riscv-non-isa/riscv-toolchain-conventions

**Comment by MaskRay** [comment]
"general dynamic" is the more commonly used expansion of GD. "global dynamic" occurs very few times in Drepper's TLS ABI and the name is unfortunately used by GCC.

**Comment by kito-cheng** [comment]
@MaskRay added a note, that should...make this few more better.
