### ISSUE TITLE
A sentence makes me confused.

### ISSUE THREAD

**Issue by unicornx** [riscv-non-isa/riscv-elf-psabi-doc#282]
https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-elf.adoc#thread-local-storage

```
RISC-V uses Variant I as described by the ELF TLS specification, with tp containing the address one past the end of the TCB.
```

I'm confused by "tp containing the address one past the end of the TCB".

To my understanding, "tp containing the address of the TCB" should be fine, but with extra words like "one past the end of ", it just make me confused. What dose this mean or does it want to express sth more I have not understood?

**Comment by aswaterman** [comment]
It means that the TCB's address is (tp - sizeof(tcb)).  See the relevant glibc source code: https://github.com/bminor/glibc/blob/8162147872491bb5b48e91543b19c49a29ae6b6d/sysdeps/riscv/nptl/tls.h#L76-L78

**Comment by unicornx** [comment]
> It means that the TCB's address is (tp - sizeof(tcb)). See some of the relevant glibc source code, for example: https://github.com/bminor/glibc/blob/8162147872491bb5b48e91543b19c49a29ae6b6d/sysdeps/riscv/nptl/tls.h#L76-L78

So, for riscv, the thread pointer tp points to the end of the TCB, not the begin of the TCB, right? 
I was confused because I see it says "RISC-V uses Variant I as described by the ELF TLS specification,  ..." so I thought it should points to the beginning of the TCB, as in https://www.akkadia.org/drepper/tls.pdf

![image](https://user-images.githubusercontent.com/2476165/168511741-150e85cc-d67b-4bdc-abad-155626855cbb.png)
 
I would suggest we emphasize this out by changing existing sentence "RISC-V uses Variant I as described by the ELF TLS specification, with tp containing the address one past the end of the TCB." to "RISC-V uses Variant I as described by the ELF TLS specification, but differs in that tp contains the address one past the end of the TCB."

**Comment by jrtc27** [comment]
tp_t is the abstract thread pointer that points to the TCB. What ends up in a physical register isn't necessarily that; PowerPC and MIPS bias it by 0x7000. The confusion stems because the RISC-V register is called tp and thus isn't so clearly distinguished from the abstract tp_t. All Variant I means is that the layout is like that, including that you can determine both the start and end of the TCB.

**Comment by unicornx** [comment]
Thanks all. It really confused me for long time. 
Maybe in riscv elf spec, "The thread pointer tp points to the end of the TCB." is a more clear description. I see similar sentence in <https://github.com/bminor/glibc/blob/8162147872491bb5b48e91543b19c49a29ae6b6d/sysdeps/riscv/nptl/tls.h#L63>

**Comment by jrtc27** [comment]
End is ambiguous, could be `p + sizeof - 1` or `p + sizeof`. One past the end is standard terminology for this.

**Comment by aswaterman** [comment]
Agreed w/@jrtc27.

**Comment by unicornx** [comment]
Thanks for your input, I will close this question now.
