### ISSUE TITLE
vxrm / vxsat vector state missing from vector register calling convention

### ISSUE THREAD

**Issue by kasanovic** [riscv-non-isa/riscv-elf-psabi-doc#287]
I assume these will be temporary state.

**Comment by aswaterman** [comment]
Suggested edit is adding `vcsr` to Table 3, indicating it's not preserved across calls.

**Comment by kito-cheng** [comment]
`vxrm` and `vxsat` was listed in the spec before but we decide to pull that out for now, see https://github.com/riscv-non-isa/riscv-elf-psabi-doc/pull/256

Currently we have two option for `vxrm` and `vxsat`
1. Explicitly say that is caller-save.
2. Define that as a global state like `fcsr` and let user to control that like a global variable.

And the staged conclusion is don't rush to decide that yet, and all vector stuffs will be high priority task after psABI 1.0 spec released.

**Comment by kasanovic** [comment]
I don’t think it makes sense to have only a part of the vector state described in the spec - either all or nothing.
But I can’t see how compilers can use the vector unit without having the calling convention established, so it seems pretty important to define this.

Reading through the thread, it seems the discussion was leaning towards 1).
Given that there is fixed-point equivalent to  fenv, then 1) makes the most sense as being the most efficient.

Looking ahead, I seriously doubt that a global rounding mode state makes sense for fixed-point code.
A global saturation flag could be desired, but alternatively an explicit additional saturation flag argument to selected routines might be more modern approach to providing this functionality.

I’d vote for going ahead with 1) just so we don’t have delay in compiling for vector code.

Krste

**Comment by aswaterman** [comment]
I agree that having a partial vector calling convention is probably worse
than having all or nothing. And the right technical answer does seem to be
making it caller-saved. I suggest adopting this right now (and if you
reject that proposal, please delete the entire vector calling convention).

**Comment by aswaterman** [comment]
I'll state more explicitly that I think this is a blocker for ratification.  A partial calling convention is the worst of both worlds: it creates constraints that can't be changed in a backwards-compatible manner, without providing sufficient guarantees to write software.

**Comment by kasanovic** [comment]
I agree with @aswaterman that this needs to be resolved for ratification - we can't have a half-finished calling convention.  It seems there is consensus on treating these as temporary state.

**Comment by kito-cheng** [comment]
Fixed via #294
