### ISSUE TITLE
Clarification on the relative order of HI20 and LO12 relocations

### ISSUE THREAD

**Issue by rui314** [riscv-non-isa/riscv-elf-psabi-doc#303]
https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-elf.adoc#absolute-addresses

> The R_RISCV_HI20 refers to an LUI instruction containing the high 20-bits to be relocated to an absolute symbol address. The LUI instruction is followed by an I-Type instruction (add immediate or load) with an R_RISCV_LO12_I relocation or an S-Type instruction (store) and an R_RISCV_LO12_S relocation.

It's not very clear to me what exactly "The LUI instruction is followed by an I-Type instruction" means. I read it as "the LUI instruction is guaranteed to appear before its corresponding I-type instruction in a section". But it can be read as "the LUI instruction is executed before its corresponding I-type instruction at runtime, but there's no guarantee on their physical locations."

Which is the intended meaning?

I'm asking this because the mold linker currently assumes that HI20 relocations always appear before LO12 (https://github.com/rui314/mold/blob/main/elf/arch-riscv64.cc#L193-L393). If this is a wrong assumption, I need to change the linkers behavior so that arbitrary order is allowed on HI20 and LO12 relocations.

**Comment by aswaterman** [comment]
The LUI comes first in program order, but as far as the static location goes, the order could be arbitrary.

**Comment by jrtc27** [comment]
It doesn’t even have to do that, the following is legal:
```
addi t0, zero, %lo(sym)
lui t1, %hi(sym)
add t0, t0, t1
# do things with t0
```
I don’t know why you’d ever want the lui to come later in program order but it’s not strictly forbidden, it’d just be foolish to do.

**Comment by aswaterman** [comment]
Right. That’s entirely legal, too.

**Comment by jrtc27** [comment]
Ugh GP relaxation probably does break that totally valid code doesn’t it… so is the spec at fault for not being restrictive or is the implementation at fault for catering only to real-world compiler output…

Anyway, Rui, you don’t mean HI20/LO12, you mean the PC-relative FOO_HI20 and PCREL_LO12, mold is relying on the order of those. For that it is explicitly not guaranteed already:

> Note the compiler emitted instructions for PC-relative symbol addresses are not necessarily sequential or in pairs. There is a constraint is that the instruction with the R_RISCV_PCREL_LO12_I or R_RISCV_PCREL_LO12_S relocation label points to a valid HI20 PC-relative relocation pointing to the symbol.

(and now I see the grammar in that needs fixing…)

**Comment by rui314** [comment]
Oh, thank you. I missed that clause in the specification. Yeah, my assumption was clearly wrong.

I still think that the sentence "The LUI instruction is followed by an I-Type instruction" is a bit misleading though. We could avoid the words "followed by" and instead say "is used in combination with" or something like that.

**Comment by aswaterman** [comment]
Agreed, see #304
