### ISSUE TITLE
R_RISCV_ALIGN is underspecified

### ISSUE THREAD

**Issue by rui314** [riscv-non-isa/riscv-elf-psabi-doc#306]
Here is the explanation of the R_RISCV_ALIGN relocation type:

> Alignment statement. The addend indicates the number of bytes occupied by nop instructions at the relocation offset. The alignment boundary is specified by the addend rounded up to the next power of two.

(https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-elf.adoc#relocations)

It says there are nop instructions at the location where a R_RISCV_ALIGN relocation points to and the relocation specifies some alignment requirement, but it's not clear _what_ has to be aligned as a result. It was not easy for me to understand that the instruction after the nop instructions has to be aligned to a specified alignment boundary.

The other thing the specification doesn't say anything (but an implementer must understand) is this: if there are 4n+2 bytes of nops (as opposed to a multiple of 4 bytes) for an R_RISCV_ALIGN, there's usually a 2-byte nop followed by 4-byte nops. So you need to remove nops from the end instead of from the beginning. I believe removing 4 bytes from the beginning yields an illegal instruction. I think this needs to be documented too.

**Comment by kito-cheng** [comment]
https://github.com/riscv-non-isa/riscv-elf-psabi-doc/pull/210 <-- did you mind take a review for this?

We decide to defer that PR due to it's close to release and no enough resource on improving that at that moment.

**Comment by asb** [comment]
I'm not sure if this repo is using any particular mechanism to track issues to be resolved as part of the ratification process (perhaps defining a new label? Or adding to a GH "project"?). But I'd propose considering resolution of this issue as a blocker.

**Comment by kito-cheng** [comment]
Yeah, we have using milestone to manage the 1.0 release, and I think introduce Github project should be good idea, asking admin from RVI to give me permission to create new project.

**Comment by kito-cheng** [comment]
Close via #210
