### ISSUE TITLE
Deprecating one of CALL and CALL_PLT?

### ISSUE THREAD

**Issue by rui314** [riscv-non-isa/riscv-elf-psabi-doc#307]
The psABI says that R_RISCV_CALL and R_RISCV_CALL_PLT had slightly different semantics but are now interchangeable. Then, why don't you deprecate one of the two and recommend always using another? I think it's better than keeping explaining newcomers that the distinction is a historical artifact and they are actually the same thing.

**Comment by rui314** [comment]
https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-elf.adoc#procedure-calls

In this section, it is explained that `call symbol` is expanded to R_RISCV_CALL while `call symbol@plt` is expanded to R_RISCV_CALL_PLT, although in the same section, it is said that the two relocation types are interchangeable. If it's interchangeable, is it legal to produce R_RISCV_CALL for `call symbol@plt` (I assume the answer is yes.) Overall the distinction is confusing. If they are completely interchangeable, IMHO we should always use the same relocation type in the specification.

**Comment by kito-cheng** [comment]
CALL is the deprecated one, thanks for point out! will update for this soon :)

**Comment by MaskRay** [comment]
I suggested this in #98.

**Comment by kito-cheng** [comment]
Close via #340
