### ISSUE TITLE
Define EM_RISCV32 for RV32?

### ISSUE THREAD

**Issue by rui314** [riscv-non-isa/riscv-elf-psabi-doc#309]
The RISC-V psABI seems to define only one machine type: `EM_RISCV`. I found it inconvenient because we can't distinguish RV64 object files from RV32 object files by looking at the `e_machine` ELF header field.

Other architectures define different `EM_` values for 32 bits and 64 bits. Examples are `EM_PPC` and `EM_PPC64`, `EM_I386` and `EM_X86_64`, `EM_ARM` and `EM_AARCH64`. Even though RV32 and RV64 aren't that different compared to i386/x86-64 or arm32/arm64, they are still incompatible, and you can't mix object files of different word widths.

Can we define `EM_RISCV32` for RV32?

**Comment by asb** [comment]
Is there any particular advantage to defining an `EM_RISCV32` vs differentiating on ELFCLASS32 vs ELFCLASS64 (which by my understanding is also stored in the ELF header, as part of the `e_ident` field.

**Comment by rui314** [comment]
Well, we can live without `EM_RISCV32`, but defining it is more conventional and aligned with other targets. For example, ARM defined `EM_AARCH64` instead of just setting `ELFCLASS64` to `e_type` with `EM_ARM`.

**Comment by asb** [comment]
It looks like EM_MIPS and EM_AMDGPU use ELFCLASS32/ELFCLASS64 as well. It definitely seems more common to have 32 vs 64-bit machine types, but we don't seem to be unique by only having one.

Just IMHO, but it feels like changing at this point would just cause confusion and tool incompatibilities without much clear gain.

**Comment by rui314** [comment]
Yeah, maybe you are right. I thought that RV32 is not supported widely yet since I'm working on Linux, but for embedding RV32 is probably way more popular than RV64. Closing this bug as it seems impractical to change it anymore. Thank you for your response!
