### ISSUE TITLE
RELAX relocation description should forward-reference the "code relaxation" chapter

### ISSUE THREAD

**Issue by asb** [riscv-non-isa/riscv-elf-psabi-doc#315]
Creating as an issue as I'm not sure how to handle cross-document forward references within the asciidoc toolchain used here. Arguably some other points should forward reference that chapter too.

Other related thoughts:
* Perhaps relaxation should be defined in the "Terms and Abbreviations" table
* "Linker relaxation" seems to be used more commonly than "code relaxation". Perhaps the name of the chapter should be adjusted to reflect this.

**Comment by asb** [comment]
Reopening as the cross-reference bit isn't handled by #326.

**Comment by kito-cheng** [comment]
Oh, yeah, thanks for notice, I am working on #327 and will back this soon :)

**Comment by kito-cheng** [comment]
Fixed via #327
