### ISSUE TITLE
Consider making a recommendation on how mismatched ELF attributes are handled by a linker/loader

### ISSUE THREAD

**Issue by asb** [riscv-non-isa/riscv-elf-psabi-doc#318]
Currently the spec says "Attributes are used to record information about an object file/binary that a linker or runtime loader
needs to check compatibility.". You might reasonably wonder what compability checks you should be performing. Therefore, I suggest the specification either:
* Makes it explicit that the behaviour of compatibility checks are out of scope of this document (i.e. it takes no position on under what circumstances a warning should be emitted vs a failure to link)
* Make a recommendation. e.g. recommending a warning but continuing to link by default.

I think @compnerd mentioned some issue related to this about linking in ELF files with no .text section (please correct me here / help link to the relevant issue).

**Comment by compnerd** [comment]
Yes, this is effectively the issue.  https://reviews.llvm.org/D106378 was the associated LLVM review.

**Comment by asb** [comment]
Looking again, the current text " Different architectures will be integrated into a superset when object files are merged." seems to imply that linkers should accept object files with mismatched attributes, as long as an ISA superset can be formed (i.e. the strings aren't fundamentally incompatible).

**Comment by kito-cheng** [comment]
All attributes has explicitly specify the merge rule now, but apparently Tag_RISCV_arch need further clarification since we have incompatible extensions e.g. `zfinx` and `f`

For ELF flags, psABI don't have any merge rule yet, we need more clarification about that.
