### ISSUE TITLE
Runtime-only relocations

### ISSUE THREAD

**Issue by rui314** [riscv-non-isa/riscv-elf-psabi-doc#319]
https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-elf.adoc#relocations

> Type
> Whether the relocation is a static or runtime relocation:
> - Static relocations are always resolved by the static linker
> - Runtime relocations can be resolved by both static and dynamic linkers

`RELATIVE`, `COPY`, `JUMP_SLOT`, `TLS_DTPMOD32`, `TLS_DTPMOD64`, `TLS_DTPREL32`, `TLS_DTPREL64`, `TLS_TPREL32`, `TLS_TPREL64` and `IRELATIVE` are runtime-only relocations. They cannot appear as an input to a static linker. That is contrary to the statement that "Runtime relocations can be resolved by both static and dynamic linkers"

**Comment by MaskRay** [comment]
Sending a patch soon to fix this.
