### ISSUE TITLE
What are GNU_VTINHERIT and GNU_VTENTRY?

### ISSUE THREAD

**Issue by rui314** [riscv-non-isa/riscv-elf-psabi-doc#320]
The psABI spec doesn't say anything other than "GNU C++ vtable hierarchy" and "GNU C++ vtable member usage". Are they deprecated relocation types? If static linkers don't have to support them, we should say so.

**Comment by kito-cheng** [comment]
That sneak in during very early stage of RISC-V, lots of target has defined their own `R_*_GNU_VTINHERIT` and `R_*_GNU_VTENTRY`, but I saw lld isn't handle any of `R_*_GNU_VTINHERIT` and `R_*_GNU_VTENTRY` at all even for arm, i386 and x86_64.

arm has mention that is deprecated relocations and explained[1] it was used in some...special toolchain (But according the name it should be used in GNU???)

```
The relocations R_ARM_GNU_VTENTRY and R_ARM_GNU_VTINHERIT have been used by
some toolchains to facilitate unused virtual function elimination during
linking.  This method is not recommended and these relocations may be made
obsolete in a future revision of this specification.  These relocations may be
safely ignored.
```

x86_64 has both relocation in binutils, but there is NO any word about that in their ABI document[2] now.

So I think we should deprecated that.

[1] https://github.com/ARM-software/abi-aa/blob/main/aaelf32/aaelf32.rst#56111deprecated-relocations
[2] https://gitlab.com/x86-psABIs/x86-64-ABI

**Comment by rui314** [comment]
Agreed. I've been in a position for many years that receives lots of bug reports/feature requests to the linkers including for exotic toolchains, but I've never heard of these relocations.

**Comment by MaskRay** [comment]
I agree that GNU_VTINHERIT and GNU_VTENTRY should be removed.
