### ISSUE TITLE
dwarf sp architectural rule ??

### ISSUE THREAD

**Issue by yuyang-ok** [riscv-non-isa/riscv-elf-psabi-doc#324]
I am exploring dwarf debug format.
in dwarf https://dwarfstd.org/doc/DWARF5.pdf page 325.
said sp should obey architectural rule.
why I cannot find any document about this??

**Comment by yuyang-ok** [comment]
![image](https://user-images.githubusercontent.com/96557710/183235623-f3cd95b3-5fc1-4e20-b0e6-04651f72b6b1.png)

**Comment by yuyang-ok** [comment]
Is "sp=cfa" apply to risc-v too?

**Comment by kito-cheng** [comment]
The short answer is yes,  "sp=cfa" apply to risc-v in general.

The longer answer is that's context-sensitive: you could use `.cfi_def_cfa` to set the cfa to another register other than `sp` like frame pointer (`s0`).

**Comment by yuyang-ok** [comment]
ok, thanks.
