### ISSUE TITLE
The virtual address space is not specified

### ISSUE THREAD

**Issue by jaypiper** [riscv-non-isa/riscv-elf-psabi-doc#346]
1. The defalut start address is 0x10000 for gcc to compile non-PIE, but we couldn't find any related information in the documentation.
2. We find that the [first related commit](https://github.com/riscvarchive/riscv-binutils-gdb/commit/e23eba971dd409b999dd83d8df0f842680c1c642#diff-c9852806d3692267f621719df8ddfa0da9bf0fe15d60f36c59869382105c2b49R22) in gnu-toolchain is in 2016, but no relevant information mentioned in commit log.
3. The virtual address space is specified in the psabi of i386, x86-64 and mips.

So it may be necessary to document the virtual address space.

**Comment by jaypiper** [comment]
@jrtc27 the detailed information is supplemented.

**Comment by jrtc27** [comment]
There are no restrictions therefore there is nothing for us to document. Larger virtual address space extensions keep being added for RV64 (Sv57 being the latest) and we don't want to create headaches like exist on x86 where the ABI is initially 48-bit but then LA57 comes along and needs to be supported somehow. The default start address is toolchain-specific and sometimes also OS-specific.
