### ISSUE TITLE
Mandatory/optional merging of build attributes

### ISSUE THREAD

**Issue by MaskRay** [riscv-non-isa/riscv-elf-psabi-doc#352]
I am concerned with the use of build attributes but I think it's useful noting down a GNU ld arm behavior regarding to `.ARM.attributes` merging.

For a tag number `tag`, if `tag%128 < 64`, the attribute is considered mandatory and GNU ld unaware of it reports an error (which will change the exit status to 1); otherwise, (`tag%128 >= 64`), the attribute is considered optional: there is a warning but the link will succeed (`--fatal-warnings` can upgrade the warning to an error).

```
% cat a.s
.eabi_attribute 88, 2
.eabi_attribute 128, 2
% arm-linux-gnueabi-gcc -nostdlib a.s a.s
/usr/lib/gcc-cross/arm-linux-gnueabi/12/../../../../arm-linux-gnueabi/bin/ld: warning: a.out: unknown EABI object attribute 88
/usr/lib/gcc-cross/arm-linux-gnueabi/12/../../../../arm-linux-gnueabi/bin/ld: a.out: unknown mandatory EABI object attribute 128
/usr/lib/gcc-cross/arm-linux-gnueabi/12/../../../../arm-linux-gnueabi/bin/ld: failed to merge target specific data of file /tmp/ccfJwSI8.o
/usr/lib/gcc-cross/arm-linux-gnueabi/12/../../../../arm-linux-gnueabi/bin/ld: warning: cannot find entry symbol _start; defaulting to 0000000000000178
collect2: error: ld returned 1 exit status
```

For RISC-V, it's perhaps useful specifying whether it's necessary to emit a warning/error when all input files with an attribute have the same value. Personally I think that's not useful. When GNU ld sees an unknown attribute only in one input, it doesn't give a warning/error.

**Comment by jrtc27** [comment]
64 seems like an arbitrary limit. If we want to do this it should probably follow the odd/even approach and use something like bit 1 to indicate whether it's optional (with special cases for existing attributes that don't fit that).

**Comment by MaskRay** [comment]
.ARM.attributes uses modular arithmetic. I originally used ` if `tag < 64 (mod 128)`. Now I changed it to `if tag%128 < 64` to make it clearer. So there is no arbitrary lower limit like 64.

**Comment by jrtc27** [comment]
Ah I missed the (mod 128), that works (and effectively is equivalent, just uses bit 6 instead of bit 1)

**Comment by kito-cheng** [comment]
I like the general idea, it sounds like more easier to linker to handle unknown attributes :)

**Comment by kito-cheng** [comment]
Created PR for this: https://github.com/riscv-non-isa/riscv-elf-psabi-doc/pull/360
