### ISSUE TITLE
Should calling convention also define ptrdiff_t?

### ISSUE THREAD

**Issue by appujee** [riscv-non-isa/riscv-elf-psabi-doc#376]
[cc-type-sizes-and-alignments](https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-cc.adoc#cc-type-sizes-and-alignments) has the definitions of types for both IPL32 and LP64 systems. Would it help to define the size of `ptrdiff_t`?

**Comment by kito-cheng** [comment]
It's good idea, I guess we should also define size_t together.

Checked with clang and gcc, thankful they are define exactly same for both RV32 and RV64.
