### ISSUE TITLE
Question about medlow's single 2 GiB address range

### ISSUE THREAD

**Issue by BigBrotherJu** [riscv-non-isa/riscv-elf-psabi-doc#442]
Not sure if this is the right place to ask questions, but I have a question about medlow code model.

The following comes straight from GCC's documentation. I want to know why "The program and its statically defined symbols must lie within **a single 2 GiB address range**" for the medlow code model.

> `-mcmodel=medlow`
>
> Generate code for the medium-low code model. The program and its statically defined symbols must lie within a single 2 GiB address range and must lie between absolute addresses −2 GiB and +2 GiB. Programs can be statically or dynamically linked. This is the default code model.

medlow code model uses `lui` `addi` to get an absolute address for global variables. As long as global variables lie between absolute addresses -2 GiB and +2 GiB, everything should work out. Why is there a **single 2 GiB range**?

For example, with 64 bit riscv gcc toolchain, I can place text at 0x6000 0000 and data at 0xffff ffff 8000 0000. The linker does not complain at all and generates an executable with no problem.

Chapter 5 of RISC-V ABIs Specification does not mention anything about this address range.

**Comment by jrtc27** [comment]
Firstly, that's GCC's documentation, so really you should ask in GCC forums why GCC says what it does. The psABI here says:

> The medium low code model, or medlow, allows the code to address the whole RV32 address space or the lower 2 GiB and highest 2 GiB of the RV64 address space (0xFFFFFFFF7FFFF800 ~ 0xFFFFFFFFFFFFFFFF and 0x0 ~ 0x000000007FFFF7FF). By using the lui and load / store instructions, when referring to an object, or addi, when calculating an address literal, for example, a 32-bit address literal can be produced.

As for where this restriction comes from, I already answered you on Reddit 7h prior to you filing this issue: https://www.reddit.com/r/RISCV/comments/1dj0et8/medlow_2gib_address_range/. To quote my reply:

> Objects can use the whole range in practice, yes, but function calls still use auipc+jalr so need to be within 2 GiB of each other.

If you arrange things carefully you can therefore have > 2 GiB, but in the general case you can't, and as a result that's what it documents.
